### ISSUE TITLE
удали

### ISSUE THREAD

**Issue by shyrkatawi** [VKTRenokh/kick-on-deafen#1]
удали плиз своего бота, спасибо!

**Comment by JiriSimonov** [comment]
@shyrkatawi  хороший бот, который позволяет модерировать голосовые канала, а ты пес

**Comment by shyrkatawi** [comment]
я звёздочку поставил, но было бы здорово что бы бота удалили! спасибо!

**Comment by VKTRenokh** [comment]
учтем
