### ISSUE TITLE
у Раджи сломалcя гит конфиг

### ISSUE THREAD

**Issue by shyrkatawi** [VKTRenokh/kick-on-deafen#10]
привет Витя, изза твоего репозитория сломался гит конфиг
почини как нибудь пожалуйста, спасибо!

**Comment by shyrkatawi** [comment]
UPDATE: он не сломался, а удалился походу))))))))))

**Comment by VKTRenokh** [comment]
я помогу ему востановить гитконфиг позже

**Comment by shyrkatawi** [comment]
@VKTRenokh  спасибо за ответ!
