### ISSUE TITLE
Измените пожалуйста правила по поводу "можно залить только свой id"

### ISSUE THREAD

**Issue by shyrkatawi** [VKTRenokh/kick-on-deafen#16]
Аннотация. В статье рассмотрены сущность, понятие бизнес-анализа, причины изменений в теории и практике анализа хозяйственной деятельности бизнес-структур. Описаны подходы проведения бизнес-анализа, результаты его применения и для каких целей провидится анализ. Отражена динамика банкротства компаний в РФ. Обоснованна роль бизнес-анализа, в решении задач по сбору и обработка информации об ожидаемых рисках, вероятности банкротства компаний.

Ключевые слова: компании, риски, бизнес-анализа, структура, модель, управленческие решения, эффективность управления, вероятность банкротства, стратегия.

На современном этапе, в связи с появлением новых потребностей и задач, а соответственно и новых целей в деятельности компаний, имеют место быть серьезные изменения в теории и практике анализа хозяйственной деятельности бизнес-структур, как зарубежных, так и российских.

Соответственно, существенно изменились такие составляющие теории экономического анализа, как предмет, функции, принципы, технология проведения аналитических исследований.

Наряду с традиционными технологиями экономического анализа, в последнее время достаточно широкое развитие получили новые методы и подходы, которые удовлетворяют потребностям стратегического управления: непрерывное прогнозирование, учет влияния внешней среды, система сбалансированных показателей, модель экономической добавленной стоимости, учет и анализ затрат по видам деятельности и др.

**Comment by VKTRenokh** [comment]
нет
