### ISSUE TITLE
Сходите пожалуйста туда куда Вас отправил Раджи

### ISSUE THREAD

**Issue by shyrkatawi** [VKTRenokh/kick-on-deafen#17]
Уважаемый Витя(утя), не соизволите ли Вы отправится в некое путешествие?

**Comment by VKTRenokh** [comment]
![wp2618927-1521128640](https://github.com/VKTRenokh/kick-on-deafen/assets/105741866/b5efbf21-3c5b-45e5-8aee-bbefc049de06)
